
---
title: "HIV Report Update"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
params:
  my_param: "default_value"
  production: TRUE
  cutpoint: 50
---

```{}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```




```{r, load-data}
data_url <- "https://bit.ly/vrc01_data"
data <- read.csv(data_url, header = TRUE)
```

# Descriptive Analysis

```{r}
library(ggplot2)

ggplot(data, aes(x = shield_glycans, y = ab_resistance)) +
geom_point() +
geom_smooth(method = "lm") +
theme_bw()

```



# Regression Analysis

## Primary model


  

```{r}
mod <- glm(
ab_resistance ~ shield_glycans + region + env_length,
data = data
)

summary(mod)

```


## Graphical analysis

Below we report a scatter plot of antibody resistance as a function of 
number of PNGs in the glycan shield. 

```{r, plot-data}
library(dplyr)

secondary_data <- data %>%
select(ab_resistance, shield_glycans, region, env_length) %>%
na.omit()

binary_mod <- glm(
I(ab_resistance > params$cutpoint) ~ shield_glycans + region + env_length,
data = secondary_data,
family = binomial()
)

summary(binary_mod)

```



# Regression Analysis

## Primary model

```{r, fit-primary-model}
mod <- glm(
  ab_resistance ~ shield_glycans + region + env_length,
  data = data
)



```


```{r}
## Secondary model (binary outcome)

secondary_data <- data |>
  dplyr::select(ab_resistance, shield_glycans, region, env_length) |>
  na.omit()

binary_mod <- glm(
  I(ab_resistance > params$cutpoint) ~ shield_glycans + region + env_length,
  data = secondary_data,
  family = binomial()
)

summary(binary_mod)

```
